<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" exclude-result-prefixes="html" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml" xmlns:html="http://www.w3.org/1999/xhtml">
  <xsl:output omit-xml-declaration="yes" indent="yes"/>
  <xsl:template match="abstract"><div class="render-abstract"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="action-date"><div class="render-action-date"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="address"><div class="render-address"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="addressbook"><div class="render-addressbook"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="agent"><div class="render-agent"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="agents"><div class="render-agents"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="application-reference"><div class="render-application-reference"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="assignee"><div class="render-assignee"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="assignees"><div class="render-assignees"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="assistant-examiner"><div class="render-assistant-examiner"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="claim"><div class="render-claim"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="claim-text"><div class="render-claim-text"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="claims"><div class="render-claims"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="classification-ipcr"><div class="render-classification-ipcr"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="classification-national"><div class="render-classification-national"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="classifications-ipcr"><div class="render-classifications-ipcr"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="colspec"><div class="render-colspec"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="description"><div class="render-description"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="description-of-drawings"><div class="render-description-of-drawings"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="document-id"><div class="render-document-id"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="drawings"><div class="render-drawings"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="entry"><div class="render-entry"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="examiners"><div class="render-examiners"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="figure"><div class="render-figure"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="figures"><div class="render-figures"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="generating-office"><div class="render-generating-office"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="img"><div class="render-img"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="inventor"><div class="render-inventor"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="inventors"><div class="render-inventors"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="ipc-version-indicator"><div class="render-ipc-version-indicator"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="nplcit"><div class="render-nplcit"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="p"><div class="render-p"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="patcit"><div class="render-patcit"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="primary-examiner"><div class="render-primary-examiner"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="priority-claim"><div class="render-priority-claim"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="priority-claims"><div class="render-priority-claims"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="publication-reference"><div class="render-publication-reference"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="related-publication"><div class="render-related-publication"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="residence"><div class="render-residence"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="row"><div class="render-row"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="table"><div class="render-table"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="tables"><div class="render-tables"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="tbody"><div class="render-tbody"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="tgroup"><div class="render-tgroup"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="thead"><div class="render-thead"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-applicant"><div class="render-us-applicant"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-applicants"><div class="render-us-applicants"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-bibliographic-data-grant"><div class="render-us-bibliographic-data-grant"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-citation"><div class="render-us-citation"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-field-of-classification-search"><div class="render-us-field-of-classification-search"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-parties"><div class="render-us-parties"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-patent-grant"><div class="render-us-patent-grant"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-provisional-application"><div class="render-us-provisional-application"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-references-cited"><div class="render-us-references-cited"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-related-documents"><div class="render-us-related-documents"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="us-term-of-grant"><div class="render-us-term-of-grant"><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="additional-info"><span class="render-additional-info"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="b"><span class="render-b"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="category"><span class="render-category"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="city"><span class="render-city"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="claim-ref"><span class="render-claim-ref"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="class"><span class="render-class"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="classification-data-source"><span class="render-classification-data-source"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="classification-level"><span class="render-classification-level"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="classification-status"><span class="render-classification-status"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="classification-value"><span class="render-classification-value"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="country"><div class="render-country"><label>Country:</label><xsl:apply-templates/></div></xsl:template>
  <xsl:template match="date"><span class="render-date"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="department"><span class="render-department"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="doc-number"><span class="render-doc-number"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="figref"><span class="render-figref"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="first-name"><span class="render-first-name"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="further-classification"><span class="render-further-classification"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="heading"><span class="render-heading"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="invention-title"><span class="render-invention-title"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="kind"><span class="render-kind"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="last-name"><span class="render-last-name"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="main-classification"><span class="render-main-classification"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="main-group"><span class="render-main-group"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="name"><span class="render-name"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="number-of-claims"><span class="render-number-of-claims"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="number-of-drawing-sheets"><span class="render-number-of-drawing-sheets"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="number-of-figures"><span class="render-number-of-figures"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="orgname"><span class="render-orgname"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="othercit"><span class="render-othercit"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="role"><span class="render-role"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="section"><span class="render-section"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="state"><span class="render-state"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="subclass"><span class="render-subclass"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="subgroup"><span class="render-subgroup"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="symbol-position"><span class="render-symbol-position"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="us-application-series-code"><span class="render-us-application-series-code"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="us-claim-statement"><span class="render-us-claim-statement"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="us-exemplary-claim"><span class="render-us-exemplary-claim"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="us-term-extension"><span class="render-us-term-extension"><xsl:apply-templates/></span></xsl:template>
  <xsl:template match="html:*"><xsl:copy><xsl:copy-of select="@*"/><xsl:apply-templates/></xsl:copy></xsl:template>
</xsl:stylesheet>