//app.js - generated by MarkLogic Appbuilder 2.0 2014-01-25T01:25:08.151292-05:00

ML.controller.init(controller_config);

var search = ML.createSearch("search");
  
var sidebar = ML.createSidebar("sidebar", sidebar_config);
  
var column_1 = ML.chartWidget("widget-1", "column", column_config_1);
var pie_2 = ML.chartWidget("widget-2", "pie", pie_config_2);


var results = ML.createResults("results", results_config);          
  


ML.controller.loadData();

